global_config:
  seed: &seed_value 2


NestedCV:
  iterator_key: combined_dataset_iterators
  split_key: full
  config:
    num_outer_loop_folds: 5
    num_inner_loop_folds: 2
    inner_stratification: true
    outer_stratification: true
    target_pos: 1
    shuffle: false
    seed: *seed_value
