run_configuration:
  type: train # train, warmstart
  config:
    num_epochs: 10 # Number of epochs
    gs_config_path: /scratch/max/mlgym/example/bert/bert_lm_config.yml

environment:
  type: multiprocessing # multiprocessing,  main_process, accelerate
  config:
    process_count: 3 # Max. number of processes running at a time.
    computation_device_ids: [5, 6] # Indices of GPUs to distribute the GS over

logging:
  websocket_logging_servers: # List of websocket logging servers, e.g., 127.0.0.1:9090 127.0.0.1:8080
    - 127.0.0.1:9090
  gs_rest_api_endpoint: 127.0.0.1:8080 # Endpoint for the grid search API, e.g., 127.0.0.1:8080

