component_1:
  component_type_key: OPTIMIZER
  variant_key: DEFAULT
  config:
    optimizer_key: ADAM
    params:
      param_x: value_123
      lr:
        sweep: absolute
        values: [0.01, 0.001, 0.0001]
      lr_2:
        - a
        - b
        - value_124