 
name: Publish package

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: python -m pip install setuptools wheel build
      
      - name: Build package
        env:
          CI: false
        run: pwd && cd src/ml_board/frontend/dashboard && npm install && npm run build && pwd && ls -lah && cd build && pwd &&  ls -lah && cd ../../../../ && pwd && python -m build --sdist --wheel

 #     - name: Publish package
 #       uses: pypa/gh-action-pypi-publish@master
 #       with:
 #         user: __token__
 #         password: ${{ secrets.pypi_password }}
 #         packages_dir: src/dist
